<a href="https://colab.research.google.com/github/diegoguanotasig/L1ML/blob/main/Sab26_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [2]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
null_counts = titanic.isnull().sum().reset_index()
null_counts.columns = ['column', 'null_count']

fig = px.bar(null_counts, x='column', y='null_count',
             title='Número de valores nulos por columna en el dataset Titanic',
             labels={'null_count': 'Conteo de valores nulos', 'column': 'Columna'})
fig.show()

In [6]:
display(null_counts)

         column  null_count
0      survived           0
1        pclass           0
2           sex           0
3           age         177
4         sibsp           0
5         parch           0
6          fare           0
7      embarked           2
8         class           0
9           who           0
10   adult_male           0
11         deck         688
12  embark_town           2
13        alive           0
14        alone           0

In [8]:
# Eliminar la columna 'deck'
titanic = titanic.drop('deck', axis=1)

# Rellenar los valores nulos en 'age' con el promedio
titanic['age'].fillna(titanic['age'].mean(), inplace=True)

print("Columna 'deck' eliminada y valores nulos de 'age' rellenados.")
# Verificar los cambios mostrando la información del DataFrame nuevamente o los primeros valores.
titanic.info()

Columna 'deck' eliminada y valores nulos de 'age' rellenados.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

/tmp/ipykernel_1760/2605473324.py:5: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [11]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [12]:
numerical_cols = titanic.select_dtypes(include=['int64', 'float64']).columns

fig = px.scatter_matrix(titanic, dimensions=numerical_cols,
                        title='Matriz de Scatterplot de Variables Numéricas en Titanic')
fig.show()

In [13]:
import plotly.graph_objects as go

# Seleccionar columnas relevantes para el análisis de correlación
# Incluimos 'survived' como la variable objetivo
relevant_cols = ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'class']
titanic_corr = titanic[relevant_cols].copy()

# Codificar la columna 'sex' (Female: 0, Male: 1) o (Male: 0, Female: 1)
titanic_corr['sex'] = titanic_corr['sex'].map({'female': 1, 'male': 0})

# Codificar la columna 'class' (Ordinal: First: 1, Second: 2, Third: 3)
titanic_corr['class'] = titanic_corr['class'].map({'First': 1, 'Second': 2, 'Third': 3})

# Calcular la matriz de correlación
correlation_matrix = titanic_corr.corr()

# Crear el heatmap de correlación con Plotly
fig = go.Figure(data=go.Heatmap(
                   z=correlation_matrix.values,
                   x=correlation_matrix.columns,
                   y=correlation_matrix.columns,
                   colorscale='Viridis',
                   colorbar=dict(title='Correlación')))

fig.update_layout(
    title='Matriz de Correlación del Dataset Titanic (Variables Clave)',
    xaxis_title='Variables',
    yaxis_title='Variables',
    xaxis_nticks=len(correlation_matrix.columns),
    yaxis_nticks=len(correlation_matrix.columns)
)

fig.show()

In [14]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB